services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: bible_db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bible_db
      SPRING_DATASOURCE_USERNAME: mysql
      SPRING_DATASOURCE_PASSWORD: mysql

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  mysql_data:
