openapi: 3.0.0
info:
  title: Bible API
  description: API for Bible application
  version: 1.0.0
  contact:
    name: Stepan Hampl
    
servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /:
    get:
      tags:
        - hello
      summary: Get hello message
      description: Returns a custom hello world message
      operationId: hello
      responses:
        '200':
          description: Hello message
          content:
            text/plain:
              schema:
                type: string
                example: "Hello world!"
  /bible/random:
    get:
      tags:
        - bible
      summary: Get random Bible verse
      description: Returns a random Bible verse from the Czech translation
      operationId: getBibleRandom
      responses:
        '200':
          description: Random Bible verse
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BibleVerseResponse'

components:
  schemas:
    BibleVerseResponse:
      type: object
      required:
        - bookName
        - chapter
        - verse
        - text
      properties:
        bookName:
          type: string
          description: Name of the Bible book
          example: "Genesis"
        chapter:
          type: integer
          description: Chapter number
          example: 1
        verse:
          type: integer
          description: Verse number
          example: 5
        text:
          type: string
          description: The verse text
          example: "Bůh nazval světlo dnem a tmu nazval nocí; a byl večer a bylo ráno, jeden den. "
